/**
 * THE CONFIG `MUTATE.command` RUNS UNDER, AND THE ONLY THING IT CHANGES IS THAT
 * THE DOC GATE IS NOT WIRED. `T-171`, ruled 2 Sep.
 *
 * ── WHY THIS FILE EXISTS ─────────────────────────────────────────────────────
 *
 * `MUTATE.command` breaks a `.compact` on purpose, compiles the break into
 * `contracts/managed`, runs `contracts/test` against it and reads which tests
 * went red. `T-167` had just replaced the doc gate's input digest with a
 * RENDER-AND-COMPARE: `scripts/doc-freshness.ts` re-renders the generated
 * blocks FROM THE COMPILED ARTIFACT and diffs the bytes. `docs/design/circuits.md`
 * carries per-circuit assert messages and assert counts read off that artifact.
 *
 * So the moment a mutation deletes or changes an `assert`, the render diverges,
 * `globalSetup` throws, no worker evaluates a test module, no `×` is printed,
 * and `MUTATE.command:1916-1932` refuses to score — *"THE SUITE DID NOT RUN —
 * aborting rather than scoring nothing"*.
 *
 * **THE MECHANISM HAS NOW BEEN WATCHED, AND NOT BY `MUTATE.command`. `S56`.**
 * That door and this gate have never run together and never will — it always
 * passes `--config`, and this gate is what the flag removes. **Its old evidence
 * WAS stale:** `REPORT-MUTATE.txt:1` now reads `Started Fri Sep  4 02:50:26 IST
 * 2026`, `112 caught`, under this config by its own `:3`. `SC9` read that as
 * *settled by a run*; **it is not — the gate was off, and no run of that door
 * can ever have it on.** What DID watch it is `scripts/mutate-authority.mjs`,
 * which passes no `--config`: its mutation 22 deletes a `pureCircuits` call
 * site `docs/design/edges.json` records, the gate threw, and vitest emitted
 * `logs/mutate-authority/mutation-22.json` — 483 bytes, 0 suites, 0 assertions
 * against 22 and 75 everywhere else in the same run.
 *
 * The mutation predicted to trip it first HERE is still `[3]` (`MUTATE.command:212`),
 * the first that deletes an `assert`: `[1]` and `[2]` (`:202`, `:207`) edit
 * `slotOf`, which `docs/design/circuits.md:69` records as `asserts 0`, so
 * neither moves a generated byte. **That holds only while `contracts/managed/keys`
 * is absent** — with keys on disk `circuits.md`'s verifier-key column would carry
 * a per-circuit measurement `[1]` would move. Rule 7 keeps them off; a condition.
 *
 * **What is not a prediction: the harness scores nothing while this stands, and
 * the change in front of it — `S35c`'s ledger layout — is the least correctable
 * edit this product will ever make.**
 *
 * ── IT IS A SCOPE CORRECTION, NOT A DISARM, AND THE DISTINCTION IS THE RULING ─
 *
 * The doc gate asks *do the documents describe the artifact on disk?* During a
 * mutation run the artifact is a DELIBERATE TEMPORARY LIE that the harness
 * restores. The documents describing the UNMUTATED contract are correct, and
 * the gate firing on a mutated artifact is a FALSE POSITIVE — it is not
 * catching a human who forgot to regenerate, which is the only thing it was
 * written to catch. Regenerating inside the loop was refused outright: it would
 * render the doc set from a contract broken on purpose, which is the exact
 * thing `scripts/doc-freshness.ts:14-21` exists to refuse and is worse than a
 * missing document.
 *
 * **AND THAT ARGUMENT DOES NOT COVER THE BASELINE, WHICH IS WHY THE BASELINE
 * HAS ITS OWN.** `MUTATE.command:1629` runs the suite BEFORE anything is
 * broken — the pristine copies are not taken until `:1752-1753` — so at that
 * moment the artifact is the real one and the doc gate firing there is a TRUE
 * positive, catching the human who forgot `DOCS.command`. `T-171` says so in
 * its own words. **The baseline runs under this config anyway, and the reason
 * is `C293` rather than false positives: the baseline exists to certify the
 * invocation the loop will use, so it must BE that invocation.** A baseline
 * stricter than the loop certifies something the loop never runs, and it aborts
 * fourteen minutes of work for a staleness that cannot move a single verdict —
 * which is the fault `MUTATE.command`'s own header already names for scope.
 * **What is given up is real and is named: a stale doc set now survives a
 * MUTATE run. `TEST.command` catches it, `T-171`'s run order puts `DOCS.command`
 * in front of `MUTATE.command`, and this file's report says so in its output.**
 *
 * `artifact-freshness` and `ledger-limit` STAY WIRED and are not negotiable. A
 * stale artifact during a mutation run makes every score meaningless — it is
 * `C294`, and `MUTATE.command:1740-1753` already had to fix a `cp` that tripped
 * it. `ledger-limit` is `C357`'s guard.
 *
 * ── IT IS DERIVED. THAT IS THE FIRST OF THE RULING'S THREE CONDITIONS ────────
 *
 * Everything below comes from `vitest.config.ts` by SPREAD. Nothing is retyped:
 * not the `include` globs, not `setupFiles`, not `testTimeout`, not `env`. A
 * second hand-maintained config is `M-104` with a new name, and it would drift
 * the first time somebody adds a guard to the real one — invisibly, because
 * both files would still look right.
 *
 * `dropDocGate` below REFUSES rather than returning the list unchanged when the
 * entry it removes is not there. A subtraction that subtracts
 * nothing is a check that cannot fail. Rename or delete
 * `doc-freshness.globalSetup.ts` and this file throws at load, naming what
 * happened, instead of quietly becoming a copy of `vitest.config.ts` under a
 * name that says it is not one.
 *
 * A test held outside the published set is the ruling's second condition: it
 * imports BOTH configs as modules, reads their values, and asserts the
 * difference is exactly this one entry with everything else deeply equal.
 *
 * **IT HAS NOT YET RUN, AND UNTIL IT HAS, "ASSERTS" IS THE WORD RATHER THAN
 * "PINS".** No vitest invocation can start in this repository right now:
 * `contracts/src/ConfidentialAccount.compact` is newer than
 * `contracts/managed/contract/index.js`, so `artifact-freshness` refuses every
 * run and names `COMPILE-CONTRACT.command`. That is `S35c`'s tree, inherited,
 * not anything this round did. **`COMPILE-CONTRACT.command`, then
 * `DOCS.command`, then `TEST.command` is what turns the assertion into a pin.**
 * Rule 19: the door, not a file to write.
 *
 * ── AND ONE THING ONLY THAT TEST FILE KEEPS ALIVE ────────────────────────────
 *
 * THIS FILE IS TYPECHECKED ONLY BECAUSE THAT TEST IMPORTS IT. It sits at the
 * repository root and matches neither `tsconfig.json`'s `include` (`src`) nor
 * `tsconfig.scripts.json`'s. `tsc` follows imports, so that test
 * is the single thread holding it inside both programs — exactly as
 * `scripts/artifact-freshness.test.ts` holds `vitest.config.ts`. **Delete or
 * skip that test file and this config silently leaves the typecheck as well as
 * losing its assertions.**
 *
 * ── WHAT THIS FILE IS NOT ────────────────────────────────────────────────────
 *
 * IT IS NOT A WAY TO RUN THE SUITE. `TEST.command` is the only door that speaks
 * for the suite, and it runs under `vitest.config.ts` with all three guards. A
 * mutation score was never a statement about documentation and must not start
 * reading as one — `MUTATE.command` says so in its own report output, in a line
 * a person reads. Rule 3 and the ruling's third condition.
 *
 * THERE IS NO ENVIRONMENT VARIABLE, FLAG OR MARKER FILE ANYWHERE IN THIS ROUTE.
 * That was considered and refused: `scripts/artifact-freshness.ts`'s header
 * warns against exactly that shape, and a guard that can be switched off from
 * inside is a guard that will be, by something that is not a door. The whole
 * point of a config file is that passing it is visible in the command line that
 * a person can read in `MUTATE.command`.
 */
import { defineConfig } from 'vitest/config';

import base from './vitest.config.ts';

/**
 * The one `globalSetup` entry a mutation run does not wire, spelled exactly as
 * `vitest.config.ts` spells it. Exported so the difference test names the same
 * string this file removes rather than a second copy of it.
 */
export const DOC_GATE = './scripts/doc-freshness.globalSetup.ts';

/**
 * The whole derivation, as a function, so it can be called against a list a
 * test controls and watched to throw.
 *
 * IT THROWS THREE WAYS, AND EACH ONE IS A STATE IN WHICH THIS FILE WOULD
 * OTHERWISE BE A COPY RATHER THAN A DERIVATION:
 *
 *   - the entry is absent — somebody renamed or removed the doc gate, and
 *     returning the list unchanged would leave a config that differs from
 *     `vitest.config.ts` in nothing at all;
 *   - the entry appears more than once — removing "one entry" would remove two;
 *   - the list is empty, or what SURVIVES the removal is — `vitest.config.ts`
 *     has stopped wiring the guards this depends on, and a mutation run under
 *     the result would be scored against no gate whatsoever.
 *
 * **THE LAST OF THOSE IS CHECKED ON THE OUTPUT AND NOT ONLY ON THE INPUT, AND
 * AN AUDITOR HAD TO SAY SO.** The first version refused an empty input and
 * described the consequence in terms of the output — which left the one path
 * that actually reaches that consequence open: a `vitest.config.ts` wiring the
 * doc gate ALONE is a non-empty input, one hit, and an empty result, produced
 * silently by the function whose comment said it prevented exactly that. A
 * guard whose written reason does not match its behaviour is the next round's
 * false confidence, and that sentence is in this repository twice in this same
 * round.
 */
export function dropDocGate(entries: readonly string[]): string[] {
  if (entries.length === 0) {
    throw new Error(
      'vitest.mutation.config.ts: vitest.config.ts wires NO globalSetup at all. This file exists ' +
        'to remove exactly one entry from that list, and there is nothing to remove from. ' +
        'artifact-freshness and ledger-limit must be wired for a mutation score to mean anything. ' +
        'C238, C263.',
    );
  }
  const hits = entries.filter((e) => e === DOC_GATE).length;
  if (hits === 0) {
    throw new Error(
      `vitest.mutation.config.ts: "${DOC_GATE}" is not among vitest.config.ts's globalSetup entries ` +
        `(${entries.join(', ')}). This file would then be an exact copy of vitest.config.ts under a ` +
        'name saying it is not one — which is the drift T-171\'s ruling wrote condition (1) to ' +
        'prevent. If the doc gate was renamed, rename DOC_GATE here in the same turn.',
    );
  }
  if (hits > 1) {
    throw new Error(
      `vitest.mutation.config.ts: "${DOC_GATE}" appears ${hits} times in vitest.config.ts's ` +
        'globalSetup. Removing "exactly one entry" would remove more than one, and the difference ' +
        'this file is allowed to make is one entry.',
    );
  }
  const kept = entries.filter((e) => e !== DOC_GATE);
  if (kept.length === 0) {
    throw new Error(
      'vitest.mutation.config.ts: removing the doc gate leaves NO globalSetup at all. A mutation ' +
        'run under that config would be scored against no gate whatsoever — a stale artifact would ' +
        'make every score meaningless (C294) and the ledger ceiling would go unchecked (C357). ' +
        'This refuses on the RESULT and not only on the input, because the input was not empty.',
    );
  }
  return kept;
}

const test = base.test;
if (test === undefined) {
  throw new Error(
    'vitest.mutation.config.ts: vitest.config.ts has no `test` block to derive from. Everything ' +
      'this file is — the include globs, setupFiles, the timeout, the two guards it keeps — comes ' +
      'from there by spread, and there is nothing to spread.',
  );
}

const wired = test.globalSetup;
const entries: readonly string[] = wired === undefined ? [] : Array.isArray(wired) ? wired : [wired];

export default defineConfig({
  ...base,
  test: {
    ...test,
    globalSetup: dropDocGate(entries),
  },
});
