/**
 * WHY THE NODE IS REFUSING OUR FEE PROOFS.
 *
 * Read-only until it finds something to fix, and then it fixes exactly one
 * thing. Nothing is proposed, approved, executed or deployed.
 *
 * THE EVIDENCE THIS EXISTS TO EXPLAIN. Every submission from every script now
 * comes back `1010: Invalid Transaction: Custom error: 170` —
 * `InvalidDustSpendProof`. The same wallet, the same account and the same
 * scripts worked the day before. A new script was blamed, then a stale cache;
 * both were wrong, and the run that proved it was the one where the KNOWN-GOOD
 * script failed identically.
 *
 * THE REMAINING HYPOTHESIS. DUST is not held, it is GENERATED by NIGHT that has
 * been registered for the purpose, and `dust.balance(now)` is a local
 * projection from that registration rather than a number read off the chain. If
 * the registration has lapsed or been superseded, the wallet keeps projecting a
 * balance the chain will not honour — and every fee proof built from it is
 * refused, while the wallet reports 5.37 x 10^18 DUST and no error.
 *
 * That would explain all of it: a balance that looks healthy, a fee estimate
 * that succeeds, and a node that refuses every proof.
 *
 * So this prints the one fact nothing else prints — whether each NIGHT UTXO is
 * still registered — and registers any that are not.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createDefaultTestLogger, StaticProofServerContainer } from '@midnight-ntwrk/testkit-js';
import { applyNetworkId, theNetwork } from '../src/midnight/network.js';
import { bringUpWallet } from './wallet-bringup.js';
import { testEnvironmentFor, startEnvironment } from './test-environment.js';

const ROOT = process.cwd();
const NETWORK = theNetwork();
/*
 * 6301, NOT 6300.
 *
 * Two proof servers run on this machine: `8.1.0` on 6300 and the pinned one on
 * 6301. The pinned image is `9.0.0-rc.3` — the prover built from the ledger
 * release the running node is built from
 * (midnight-node@d9729c13/Cargo.toml:445 -> crate-ledger-9.1.0.0-rc.3 ->
 * proof-server/Cargo.toml 9.0.0-rc.3), alongside ledger 1.0.0-rc.3, onchain
 * runtime 4.0.0-rc.3, midnight.js 5.0.0-beta.4 and compiler 0.33.0 — every one
 * of which we already match.
 *
 * IT SAID `9.0.0-rc.5_experimental` UNTIL 28 AUG 2026, on the authority of
 * Midnight's Stagenet delivery document — a draft edited forward of the running
 * network. rc.5 was published between ledger releases and is built from none
 * this node uses, which left the proof server as the single component pointed
 * at the wrong build. `docs/stagenet.md` carries the derivation;
 * `DEPLOY-PREVIEW.command:32` the full reason. The port was separately wrong in
 * every script except `sponsor-test.ts`.
 *
 * A proof server from a different line produces proofs the node's fee check
 * refuses, which is `InvalidDustSpendProof` — node error 170.
 */
const PROVER_PORT = Number(process.env.MIDNIGHT_PROVER_PORT || 6301);
const SEED_FILE = join(ROOT, '.midnight', 'wallet.seed');

const B = '\x1b[1m', D = '\x1b[2m', R = '\x1b[31m', G = '\x1b[32m', Y = '\x1b[33m', O = '\x1b[0m';
const good = (s: string) => console.log(`  ${G}✓${O} ${s}`);
const note = (s: string) => console.log(`  ${D}${s}${O}`);
const warn = (s: string) => console.log(`  ${Y}${s}${O}`);
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

async function main() {
  console.log(`\n${B}Why the node is refusing our fee proofs${O}`);
  console.log(`${D}network ${NETWORK}${O}\n`);

  if (!existsSync(SEED_FILE)) throw new Error(`no wallet at ${SEED_FILE}`);
  const masterSeed = readFileSync(SEED_FILE, 'utf8').trim();
  await applyNetworkId(NETWORK);

  const logger = createDefaultTestLogger();
  const { env, how } = testEnvironmentFor(NETWORK, logger);
  note(how.split('\n')[0]);
  const cfg = await startEnvironment(env, new StaticProofServerContainer(PROVER_PORT), note);
  good(`node ${cfg.node}`);

  const live = await bringUpWallet(logger, cfg, masterSeed, NETWORK, ROOT, {
    withDust: true,
    // Deliberately NOT requiring dust: a wallet that cannot pay is precisely
    // what this script exists to diagnose, so refusing to hand one back would
    // throw away the evidence.
    requireDust: false,
    onNote: note,
  });
  const wallet: any = (live as any).wallet ?? live;

  const state = () => (live as any).state?.() ?? (wallet as any).state?.();
  const NIGHT = (await import('@midnight-ntwrk/midnight-js-protocol/ledger'))
    .unshieldedToken() as any;
  const nightRaw = NIGHT.raw ?? NIGHT;

  const s = state();
  const coins: any[] = s?.unshielded?.availableCoins ?? [];
  const night = coins.filter((c: any) => c.utxo?.type === nightRaw);

  console.log(`\n${B}Every NIGHT the wallet holds${O}\n`);
  if (night.length === 0) warn('none at all — that alone would explain everything');
  let unregistered: any[] = [];
  for (const c of night) {
    const reg = c?.meta?.registeredForDustGeneration;
    const mark = reg === true ? `${G}registered${O}` : reg === false ? `${R}NOT REGISTERED${O}` : `${Y}unknown${O}`;
    console.log(`    ${String(c?.utxo?.value ?? '?').padStart(14)}  ${mark}`);
    if (reg !== true) unregistered.push(c);
  }

  let dust = 0n;
  try { dust = BigInt(s?.dust?.balance(new Date()) ?? 0n); } catch { /* ignore */ }
  console.log('');
  console.log(`  DUST the wallet PROJECTS:  ${dust}`);
  console.log(`  ${D}a local calculation from the registration above, not a number read off${O}`);
  console.log(`  ${D}the chain. A healthy-looking figure here proves nothing on its own —${O}`);
  console.log(`  ${D}which is exactly how this went undiagnosed for four runs.${O}`);

  /*
   * FORCE, because the flag is the thing under suspicion.
   *
   * The deploy after the reset printed "nothing left to register; the NIGHT may
   * already be registered" and skipped registration entirely — then reported
   * DUST going from 0 to 5.4 x 10^18 with no registration transaction anywhere
   * in the log. So the wallet believes in a registration the chain has no
   * record of, and every fee proof built from that belief is refused.
   *
   * Registering only what the flag calls unregistered cannot recover from a
   * wrong flag. With --force this registers every NIGHT UTXO regardless of what
   * the flag claims, and the chain gets the last word: either the registration
   * lands, or it is refused and we learn something specific instead of being
   * stuck behind a boolean nobody can verify.
   */
  const force = process.argv.includes('--force');
  if (force && unregistered.length === 0 && night.length > 0) {
    console.log(`\n${Y}${B}--force: registering all ${night.length} NIGHT UTXO(s) anyway.${O}`);
    console.log(`  ${D}The flag says they are registered. The node disagrees with the proofs${O}`);
    console.log(`  ${D}built on that assumption, so the flag is what gets tested here.${O}`);
    unregistered = night;
  }

  if (unregistered.length === 0) {
    console.log(`\n${B}Every NIGHT UTXO is registered.${O}`);
    console.log(`  ${D}Run this again with --force to register anyway and let the chain decide.${O}`);
    console.log('  So the registration is NOT the explanation, and the cause is elsewhere —');
    console.log('  most likely on the network side: a runtime upgrade on Stagenet would');
    console.log('  invalidate proofs built by our pinned proof server without changing');
    console.log('  anything we control. That is the next thing to check, and it is not');
    console.log('  something this script can fix.');
    return;
  }

  console.log(`\n${B}${unregistered.length} NIGHT UTXO(s) are not registered for DUST generation.${O}`);
  console.log('  That is very likely the whole answer. Registering them now.\n');

  await sleep(5000);
  const recipe = await wallet.wallet.registerNightUtxosForDustGeneration(
    unregistered,
    wallet.unshieldedKeystore.getPublicKey(),
    // signDataAsync, not signData — see the note in deploy-preview.ts.
    (payload: Uint8Array) => wallet.unshieldedKeystore.signDataAsync(payload),
  );
  const finalised = await wallet.wallet.finalizeRecipe(recipe);
  const txId = await wallet.wallet.submitTransaction(finalised);
  good(`registration submitted, tx ${String(txId).slice(0, 24)}…`);

  console.log('\n  DUST accrues over time rather than arriving at once. Waiting up to ten');
  console.log('  minutes for the chain to start generating against the new registration.');
  const started = Date.now();
  while (Date.now() - started < 10 * 60_000) {
    await sleep(5000);
    const now = state();
    const regs = (now?.unshielded?.availableCoins ?? [])
      .filter((c: any) => c.utxo?.type === nightRaw && c?.meta?.registeredForDustGeneration === true).length;
    if (regs > 0) { good(`${regs} NIGHT UTXO(s) now registered on chain`); break; }
    note(`  ${Math.round((Date.now() - started) / 1000)}s …`);
  }

  console.log(`\n${B}Now run RUN-PROPOSAL.command again.${O}`);
  console.log('  If the fee proofs verify, this was the cause and every script recovers.');
}

main().then(() => process.exit(0)).catch((e: any) => {
  console.error(`\n${R}${B}stopped:${O} ${String(e?.message ?? e)}`);
  console.error(e?.stack ?? '');
  process.exit(1);
});
