/**
 * WHICH WALLETS THIS BROWSER HOLDS, AND WHICH COMPARTMENT EACH ONE'S RECORDS
 * LIVE IN.
 *
 * Until this change `storage.ts` kept every record at a fixed `localStorage`
 * key, so writing a second wallet overwrote the first. **One wallet per
 * browser profile was never a policy; it was the shape of the keys.** This
 * file is the shape that replaces it, and `storage.ts` is the only importer.
 *
 * IT IMPORTS NOTHING FROM `storage.ts`, on purpose — `subwallets.ts`'s rule.
 * The key names, the slot list and the open slot are all decided here; the
 * records themselves are decided there; the dependency runs one way and there
 * is no cycle to unpick later.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THE ONE DECISION EVERYTHING ELSE FOLLOWS FROM: THE FIRST WALLET DOES NOT
 * MOVE.
 *
 * A slot is a string. **The slot named by the empty string is the fixed keys
 * this wallet has always used** — `midnight-identity:keyring` and its six
 * siblings, `seal` in IndexedDB, `balance-checkpoints` beside it. Every
 * ADDITIONAL wallet gets a generated id and lives under
 * `midnight-identity:w:<id>:<record>`.
 *
 * **So a browser that held one wallet before this change has nothing migrated,
 * because nothing needs to move.** No copy, no verify, no sweep, no partially
 * migrated state to reason about, and no window in which a record exists in
 * neither place. The design names the risk it was most
 * afraid of — *"a migration that silently drops a record is indistinguishable
 * from losing somebody's wallet"* — and the cheapest way to answer that fear
 * is to not perform one.
 *
 * WHAT THE ASYMMETRY COSTS, said rather than left to be found: two key shapes
 * exist instead of one, and every reader has to go through `keyFor` to know
 * which. That is one function and one rule. The alternative was moving the
 * sealed secret of every existing tester's wallet on the first load after an
 * upgrade, to buy tidier strings.
 *
 * **THE SLOT IS NOT AN IDENTITY.** It is a shelf. The same discipline — a
 * record carries the fingerprint of the secret it belongs to and is refused
 * for any other — is unchanged, still lives in `storage.ts`, and is still what
 * stops wallet B's names appearing over wallet A. This file decides only which
 * shelf a record is on.
 * ────────────────────────────────────────────────────────────────────────────
 *
 * THE DIRECTORY IS AN INDEX, NEVER THE ONLY EVIDENCE. `heldWallets` returns
 * the union of what the directory record lists and what is actually ON DISK
 * (`discoverSlots`, which reads the key names). A damaged or missing directory
 * therefore hides no wallet — it costs a name and an ordering, not access —
 * which is the same judgement `storage.ts` makes about every other decoration:
 * damage is absence, and absence must never be a wallet out of reach.
 */

/** The compartment the fixed keys are. Never generated; never re-shaped. */
export const ORIGINAL_SLOT = '';

/**
 * THE RECORDS ONE WALLET OWNS. Every one of these was a fixed key before this
 * change, and all seven move together or the split is a hole: a wallet whose
 * name is namespaced and whose passkeys are not is a wallet that opens with
 * somebody else's credential.
 */
export type RecordKind =
  | 'keyring'
  | 'passkeys'
  | 'secured'
  | 'arrived'
  | 'created'
  | 'subwallets'
  | 'wallet-name';

export const RECORD_KINDS: readonly RecordKind[] = Object.freeze([
  'keyring', 'passkeys', 'secured', 'arrived', 'created', 'subwallets', 'wallet-name',
]);

const PREFIX = 'midnight-identity';
/** `w:` is what makes a generated slot's keys unable to collide with a record
 * name: no fixed key this app has ever written begins `midnight-identity:w:`. */
const SLOT_INFIX = 'w';
const DIRECTORY = `${PREFIX}:wallets`;

/** Where one wallet's record of a kind lives. The only key builder. */
export function keyFor(walletId: string, kind: RecordKind): string {
  return walletId === ORIGINAL_SLOT
    ? `${PREFIX}:${kind}`
    : `${PREFIX}:${SLOT_INFIX}:${walletId}:${kind}`;
}

/**
 * The IndexedDB entry holding this wallet's non-extractable sealing key.
 *
 * **THE SEALING KEY IS PART OF THE SPLIT, NOT AN EXCEPTION** — the design says
 * so, and the reason is removal: taking a wallet off this browser has to be
 * able to destroy the key that opens it without touching the key that opens
 * anything else. The original wallet keeps the entry it already has, so no
 * CryptoKey is ever moved, copied or regenerated by this change.
 */
export function sealKeyFor(walletId: string): string {
  return walletId === ORIGINAL_SLOT ? 'seal' : `seal:${walletId}`;
}

/**
 * Where this wallet's balance checkpoints live. A checkpoint is a CACHE
 * (`storage.ts`, `WalletCheckpoint`) and every failure there reads as absence,
 * so this is the one record whose split could have been skipped: entries are
 * already refused unless they name the asking wallet's own coin public key, so
 * two wallets sharing the store leaked nothing. They did EVICT each other —
 * both wallets keep an entry for account 0 — and a cache two wallets take
 * turns destroying is a cold sync on every switch.
 */
export function checkpointKeyFor(walletId: string): string {
  return walletId === ORIGINAL_SLOT
    ? 'balance-checkpoints'
    : `balance-checkpoints:${walletId}`;
}

/** What this browser knows about one wallet WITHOUT opening it. */
export interface HeldWallet {
  /** The compartment its records are in. `ORIGINAL_SLOT` for the first. */
  readonly id: string;
  /**
   * base64url of `fingerprintOf` the secret this slot holds — the same value
   * every record inside carries — or NULL for a wallet that predates this
   * change, whose secret is sealed and whose fingerprint therefore cannot be
   * known until somebody opens it. See `claimFingerprint`.
   */
  readonly fingerprint: string | null;
  /** When this browser started holding it. 0 for one it has always held. */
  readonly addedAt: number;
}

interface Directory {
  readonly version: 1;
  readonly wallets: readonly HeldWallet[];
  /** The one the app opens into. Null until a browser holds more than one. */
  readonly openId: string | null;
}

const isNamed = (value: unknown): boolean =>
  typeof value === 'string' && value.trim() !== '';

function parseDirectory(raw: string): Directory | null {
  let parsed: Directory;
  try {
    parsed = JSON.parse(raw) as Directory;
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null) return null;
  if (parsed.version !== 1) return null;
  if (!Array.isArray(parsed.wallets)) return null;
  const wallets: HeldWallet[] = [];
  for (const wallet of parsed.wallets) {
    if (typeof wallet !== 'object' || wallet === null) return null;
    if (typeof wallet.id !== 'string') return null;
    if (wallet.fingerprint !== null && !isNamed(wallet.fingerprint)) return null;
    if (typeof wallet.addedAt !== 'number' || !Number.isFinite(wallet.addedAt)) return null;
    wallets.push({ id: wallet.id, fingerprint: wallet.fingerprint, addedAt: wallet.addedAt });
  }
  const openId = typeof parsed.openId === 'string' ? parsed.openId : null;
  return { version: 1, wallets, openId };
}

function readDirectory(): Directory | null {
  const raw = localStorage.getItem(DIRECTORY);
  if (!raw) return null;
  return parseDirectory(raw);
}

function writeDirectory(next: Directory): void {
  localStorage.setItem(DIRECTORY, JSON.stringify(next));
}

/**
 * THE SLOTS THAT ACTUALLY HAVE RECORDS ON DISK, read from the key names.
 *
 * This is the safety net under the directory: a wallet is found because its
 * records are there, not because an index says so. It is also what makes a
 * browser that predates this change work with no write at all — the original
 * slot is discovered exactly as any other is.
 *
 * A `localStorage` that cannot be enumerated (the ten-line stand-in some tests
 * install, a hostile shim) degrades to the directory alone rather than
 * throwing: this is a net, and a net that can bring the app down is worse than
 * no net.
 */
function discoverSlots(): readonly string[] {
  const found = new Set<string>();
  for (const kind of RECORD_KINDS) {
    if (localStorage.getItem(keyFor(ORIGINAL_SLOT, kind)) !== null) {
      found.add(ORIGINAL_SLOT);
      break;
    }
  }
  const store = localStorage as unknown as {
    length?: number; key?: (index: number) => string | null;
  };
  if (typeof store.length !== 'number' || typeof store.key !== 'function') {
    return [...found];
  }
  const head = `${PREFIX}:${SLOT_INFIX}:`;
  for (let i = 0; i < store.length; i += 1) {
    const key = store.key(i);
    if (key === null || !key.startsWith(head)) continue;
    const rest = key.slice(head.length);
    const cut = rest.indexOf(':');
    if (cut <= 0) continue;
    const id = rest.slice(0, cut);
    const kind = rest.slice(cut + 1);
    if ((RECORD_KINDS as readonly string[]).includes(kind)) found.add(id);
  }
  return [...found];
}

/**
 * EVERY WALLET THIS BROWSER HOLDS — the directory's entries first, in the
 * order it kept them, then any slot found on disk that the directory does not
 * list. The second half is why a lost directory is a lost label rather than a
 * lost wallet.
 */
export function heldWallets(): readonly HeldWallet[] {
  const directory = readDirectory();
  const listed = directory?.wallets ?? [];
  const known = new Set(listed.map((wallet) => wallet.id));
  const extra: HeldWallet[] = [];
  for (const id of discoverSlots()) {
    if (!known.has(id)) extra.push({ id, fingerprint: null, addedAt: 0 });
  }
  return [...listed, ...extra];
}

export function heldWallet(id: string): HeldWallet | null {
  return heldWallets().find((wallet) => wallet.id === id) ?? null;
}

/**
 * A slot id for a wallet about to land. The original compartment when nothing
 * holds it — a virgin browser's first wallet gets the same keys this app has
 * always written, so nothing about a one-wallet browser is new — and sixteen
 * random bytes otherwise.
 *
 * IT IS RE-OFFERED AFTER A REMOVAL, deliberately: `forgetWallet` clears the
 * compartment, and an empty compartment is a shelf, not a grave.
 */
export function allocateWalletId(): string {
  const held = heldWallets();
  if (!held.some((wallet) => wallet.id === ORIGINAL_SLOT)) return ORIGINAL_SLOT;
  let id = '';
  do {
    id = [...crypto.getRandomValues(new Uint8Array(8))]
      .map((byte) => byte.toString(16).padStart(2, '0')).join('');
  } while (held.some((wallet) => wallet.id === id));
  return id;
}

/**
 * Records that this browser holds a wallet in this slot. Called by
 * `saveSecret` and by nothing else — **the only thing that may create an
 * entry is the act of sealing a secret into the compartment**, which is what
 * makes a null fingerprint mean "predates this" and never "a wallet
 * halfway through landing".
 */
export function rememberWallet(id: string, fingerprint: string | null, now: number): void {
  const directory = readDirectory();
  const existing = heldWallets();
  const wallets = existing.map((wallet) => (wallet.id === id
    ? { ...wallet, fingerprint: fingerprint ?? wallet.fingerprint }
    : wallet));
  if (!wallets.some((wallet) => wallet.id === id)) {
    wallets.push({ id, fingerprint, addedAt: now });
  }
  writeDirectory({ version: 1, wallets, openId: directory?.openId ?? null });
}

/**
 * THE ONE MUTATION ON A READ PATH IN THIS FILE, AND WHY IT IS NOT A BREACH.
 *
 * A wallet that predates this change has a null fingerprint, because the only
 * way to compute one is to hold the secret and the secret is sealed. The first
 * time anything in `storage.ts` is called WITH that wallet's secret in hand,
 * the answer is finally available and it is written down.
 *
 * The rule forbids a READ that silently repairs a damaged record, because the
 * repair destroys the evidence of the damage. Nothing here is damaged and
 * nothing is destroyed: an unknown becomes known, once, from the only evidence
 * that could ever settle it. **It is refused when the slot already carries a
 * different fingerprint** — that is a disagreement, not an unknown, and
 * `storage.ts` turns it into a refusal to write rather than a quiet overwrite.
 */
export function claimFingerprint(id: string, fingerprint: string): void {
  const wallet = heldWallet(id);
  if (wallet === null) return;
  if (wallet.fingerprint !== null) return;
  const directory = readDirectory();
  const wallets = heldWallets().map((held) => (held.id === id
    ? { ...held, fingerprint }
    : held));
  writeDirectory({ version: 1, wallets, openId: directory?.openId ?? null });
}

/** Takes the wallet out of the index. The RECORDS are `storage.ts`'s to
 * destroy, and it does that first — an entry with no records is a stale label,
 * records with no entry are still found by `discoverSlots`. */
export function forgetWallet(id: string): void {
  const directory = readDirectory();
  const wallets = heldWallets().filter((wallet) => wallet.id !== id);
  const stillOpen = directory?.openId === id ? null : directory?.openId ?? null;
  writeDirectory({ version: 1, wallets, openId: stillOpen });
  /* AND THIS WINDOW STOPS POINTING AT IT. A window whose choice has just been
   * destroyed would otherwise go on reading and WRITING through a compartment
   * that is no longer a wallet — the next landing would find it empty and
   * settle there, which is right, but every read until then would answer
   * "nothing here" while other wallets sat beside it. The choice is cleared
   * HERE rather than guessed at in `openWalletId`, because removal is the one
   * moment this file can tell an empty compartment from a landing in flight. */
  if (openId === id) openId = undefined;
}

/**
 * WHICH WALLET THIS WINDOW HAS OPEN.
 *
 * MODULE STATE, AND THAT IS THE POINT: this origin can have two windows, and
 * each of them is looking at one wallet. A window that opened wallet A must go
 * on writing A's records even after another window opens B — which a purely
 * stored answer could not do, and which is the difference between a name
 * landing on the right wallet and landing on whichever was touched last.
 *
 * The STORED `openId` is only the default the next load starts from.
 */
let openId: string | undefined;

/**
 * The open slot, always a string. `ORIGINAL_SLOT` is the answer for a browser
 * that holds nothing, which is correct rather than convenient: it is the
 * compartment the first wallet will land in, and every read of it is empty.
 */
export function openWalletId(): string {
  if (openId !== undefined) return openId;
  const held = heldWallets();
  if (held.length === 0) return ORIGINAL_SLOT;
  const stored = readDirectory()?.openId ?? null;
  if (stored !== null && held.some((wallet) => wallet.id === stored)) return stored;
  return held[0]!.id;
}

/** Opens a slot for THIS window, and remembers it as the next load's default. */
export function openWallet(id: string): void {
  openId = id;
  const directory = readDirectory();
  const wallets = heldWallets();
  if (!wallets.some((wallet) => wallet.id === id)) return;
  if (directory?.openId === id) return;
  writeDirectory({ version: 1, wallets, openId: id });
}

/** For tests and for a window that has closed a wallet without opening
 * another: forget this window's choice and fall back to the stored default. */
export function forgetOpenWallet(): void {
  openId = undefined;
}
